"""empty message

Revision ID: 62545286a98c
Revises: 
Create Date: 2023-04-27 20:45:11.541957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62545286a98c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advice__collection',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('advice_ID', sa.String(length=150), nullable=False),
    sa.Column('advice', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('advice__collection')
    # ### end Alembic commands ###
