"""empty message

Revision ID: 90ae408dac16
Revises: 
Create Date: 2023-05-02 17:02:35.077800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90ae408dac16'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advice',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('advice', sa.String(length=500), nullable=False),
    sa.Column('user_ID', sa.String(length=300), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('advice')
    # ### end Alembic commands ###
