"""empty message

Revision ID: 9f01e9ceeeb4
Revises: f79d98ea3b94
Create Date: 2023-05-02 16:11:35.503168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f01e9ceeeb4'
down_revision = 'f79d98ea3b94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('advice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_ID', sa.String(length=300), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('advice', schema=None) as batch_op:
        batch_op.drop_column('user_ID')

    # ### end Alembic commands ###
