"""empty message

Revision ID: cdb994cf4014
Revises: 62545286a98c
Create Date: 2023-05-01 12:08:16.007739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdb994cf4014'
down_revision = '62545286a98c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('advice__collection', 'advice_ID')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('advice__collection', sa.Column('advice_ID', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
