"""empty message

Revision ID: f79d98ea3b94
Revises: cdb994cf4014
Create Date: 2023-05-01 12:29:22.925681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f79d98ea3b94'
down_revision = 'cdb994cf4014'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advice',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('advice', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('advice__collection')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advice__collection',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('advice', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='advice__collection_pkey')
    )
    op.drop_table('advice')
    # ### end Alembic commands ###
